Repository dotnet/docs.ru-ru, pull requests merged in 2018-07, with the labels that each got.

#116 Update async-return-types.md
  docs/csharp/programming-guide/concepts/async/async-return-types.md
Labels: Accepted, Source Issue

#118 Update anonymous-types.md
  docs/csharp/programming-guide/classes-and-structs/anonymous-types.md
Labels: Accepted, Linguistic Suggestion

#120 Correction of typos
  docs/csharp/language-reference/operators/index.md
Labels: Accepted, Linguistic Suggestion

#121 Update ref-returns.md
  docs/csharp/programming-guide/classes-and-structs/ref-returns.md
Labels: In Progress, Linguistic Suggestion, Source Issue
