Repository dotnet/docs.ru-ru, pull requests merged in 2018-09, with the labels that each got.

#125 Changing the word "подписанный" to "знаковый"
  docs/standard/numerics.md
Labels: Accepted, Linguistic Suggestion

#126 Опечатка. Замена "на" на "не"
  docs/standard/threading/mutexes.md
Labels: Accepted, In Progress, Linguistic Suggestion

#129 Update destructors.md
  docs/csharp/programming-guide/classes-and-structs/destructors.md
  docs/standard/garbage-collection/implementing-dispose.md
Labels: Accepted, Linguistic Suggestion

#131 Исправил опечатку
  docs/csharp/programming-guide/classes-and-structs/using-constructors.md
Labels: In Progress, Linguistic Suggestion
