Repository dotnet/docs.ru-ru, pull requests merged in 2018-03, with the labels that each got.

#94 Update windows-forms-controls-and-equivalent-wpf-controls.md
  docs/framework/wpf/advanced/windows-forms-controls-and-equivalent-wpf-controls.md
Labels: Accepted, Linguistic Suggestion

#95 Update virtual.md
  docs/csharp/language-reference/keywords/virtual.md
Labels: In Progress, Linguistic Suggestion

#77 fixing broken toc link
  docs/toc.md
Labels: Accepted, Technical Issue
