Repository dotnet/docs.ru-ru, pull requests merged in 2019-06, with the labels that each got.

#200 Ошибка в написании заголовка страницы
  docs/csharp/tour-of-csharp/interfaces.md
Labels: Accepted, Linguistic Suggestion

#201 Update cs0845.md
  docs/csharp/language-reference/compiler-messages/cs0845.md
Labels: Linguistic Suggestion, Partially Accepted

#204 Fix typo in Mutex section
  docs/standard/threading/overview-of-synchronization-primitives.md
Labels: Accepted, Linguistic Suggestion

#202 Update intro-net-docker.md
  docs/core/docker/intro-net-docker.md
Labels: Accepted, Linguistic Suggestion

#203 Improve article headings in C# Guide (part 4)
  docs/csharp/programming-guide/events/how-to-implement-custom-event-accessors.md
  docs/csharp/programming-guide/events/how-to-implement-interface-events.md
  docs/csharp/programming-guide/events/toc.yml
  docs/csharp/programming-guide/interfaces/how-to-explicitly-implement-members-of-two-interfaces.md
  docs/csharp/programming-guide/interfaces/toc.yml
  docs/csharp/programming-guide/toc.yml
  docs/csharp/programming-guide/xmldoc/index.md
Labels: Accepted, Linguistic Suggestion

#206 Fix C# Keywords TOC translation
  docs/csharp/language-reference/toc.yml
Labels: Accepted

#207 Update member-access-operators.md
  docs/csharp/language-reference/operators/member-access-operators.md
Labels: Accepted, Linguistic Suggestion

#208 Improve article headings in C# Guide (part 5)
  docs/csharp/programming-guide/namespaces/how-to-use-the-my-namespace.md
  docs/csharp/programming-guide/namespaces/toc.yml
  docs/csharp/programming-guide/nullable-types/toc.yml
  docs/csharp/programming-guide/strings/how-to-determine-whether-a-string-represents-a-numeric-value.md
  docs/csharp/programming-guide/strings/toc.yml
  docs/csharp/programming-guide/unsafe-code-pointers/how-to-use-pointers-to-copy-an-array-of-bytes.md
  docs/csharp/programming-guide/unsafe-code-pointers/toc.yml
Labels: Accepted, Linguistic Suggestion
