Repository dotnet/docs.ru-ru, pull requests merged in 2019-02, with the labels that each got.

#171 Update how-to-draw-a-line-on-a-windows-form.md
  docs/framework/winforms/advanced/how-to-draw-a-line-on-a-windows-form.md
Labels: Accepted With Changes, Linguistic Suggestion

#173 Update methods.md
  docs/csharp/programming-guide/classes-and-structs/methods.md
Labels: Accepted, Linguistic Suggestion

#172 Update three-categories-of-graphics-services.md
  docs/framework/winforms/advanced/three-categories-of-graphics-services.md
Labels: Linguistic Suggestion, Partially Accepted
